## Фреймворк PyTorch для разработки искусственных нейронных сетей
### Урок 1. Основные понятия и структуры PyTorch

- Создайте случайный FloatTensor размера 3x4x5
- Выведите его форму (shape)
- Приведите его к форме 6х10
- Создайте случайный IntTensor размера 10
- Умножьте созданный FloatTensor на созданный IntTensor поэлементно
- Умножьте тензор матрично на себя, чтобы результат был размерности 6x6 Подсказка: .dot может не подойти
- Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
- Создайте единичный тензор размера 5x6
- Переведите его в формат numpy

In [2]:
import torch

In [3]:
# Создайте случайный FloatTensor размера 3x4x5
tens = torch.randn(3, 4, 5)
tens

tensor([[[ 1.5406,  1.7202, -0.8753, -1.2383,  1.1738],
         [-0.0722, -1.0021,  1.7409,  0.1934,  2.2261],
         [ 1.3402,  0.1896,  0.3893, -0.0661,  0.1401],
         [-0.4035,  0.2250, -0.8103,  0.4741,  0.0689]],

        [[ 0.1913, -0.0402,  1.2195,  0.4730, -1.2470],
         [ 1.1284,  0.7486,  0.9409,  2.3214, -0.2181],
         [ 0.4582, -0.5771,  0.0584,  0.7614,  1.3829],
         [ 1.7638,  1.8752,  0.9071,  2.0310,  0.5721]],

        [[-0.1455, -1.4191,  1.4518,  1.4894,  2.0549],
         [ 1.7967,  0.6307, -0.4676, -0.0558,  1.3342],
         [-0.1104,  1.0897, -1.8443,  1.2044,  1.3456],
         [ 0.3415, -0.7647,  0.3111,  2.2357, -0.5298]]])

In [4]:
# Выведите его форму (shape)
tens.shape

torch.Size([3, 4, 5])

In [5]:
# Приведите его к форме 6х10
tens2 = tens.view(6, 10)
tens2

tensor([[ 1.5406,  1.7202, -0.8753, -1.2383,  1.1738, -0.0722, -1.0021,  1.7409,
          0.1934,  2.2261],
        [ 1.3402,  0.1896,  0.3893, -0.0661,  0.1401, -0.4035,  0.2250, -0.8103,
          0.4741,  0.0689],
        [ 0.1913, -0.0402,  1.2195,  0.4730, -1.2470,  1.1284,  0.7486,  0.9409,
          2.3214, -0.2181],
        [ 0.4582, -0.5771,  0.0584,  0.7614,  1.3829,  1.7638,  1.8752,  0.9071,
          2.0310,  0.5721],
        [-0.1455, -1.4191,  1.4518,  1.4894,  2.0549,  1.7967,  0.6307, -0.4676,
         -0.0558,  1.3342],
        [-0.1104,  1.0897, -1.8443,  1.2044,  1.3456,  0.3415, -0.7647,  0.3111,
          2.2357, -0.5298]])

In [6]:
# Создайте случайный IntTensor размера 10
int_tens = torch.IntTensor(10)
int_tens

tensor([-1368057968,       32732,   133589696,           0,       65280,
                  0,           8,           0,         256,           0],
       dtype=torch.int32)

In [7]:
# Умножьте созданный FloatTensor на созданный IntTensor поэлементно
tens2 * int_tens

tensor([[-2.1076e+09,  5.6306e+04, -1.1693e+08, -0.0000e+00,  7.6628e+04,
         -0.0000e+00, -8.0171e+00,  0.0000e+00,  4.9515e+01,  0.0000e+00],
        [-1.8334e+09,  6.2047e+03,  5.2010e+07, -0.0000e+00,  9.1447e+03,
         -0.0000e+00,  1.8003e+00, -0.0000e+00,  1.2136e+02,  0.0000e+00],
        [-2.6172e+08, -1.3165e+03,  1.6291e+08,  0.0000e+00, -8.1405e+04,
          0.0000e+00,  5.9891e+00,  0.0000e+00,  5.9427e+02, -0.0000e+00],
        [-6.2678e+08, -1.8890e+04,  7.8019e+06,  0.0000e+00,  9.0278e+04,
          0.0000e+00,  1.5001e+01,  0.0000e+00,  5.1994e+02,  0.0000e+00],
        [ 1.9899e+08, -4.6451e+04,  1.9395e+08,  0.0000e+00,  1.3414e+05,
          0.0000e+00,  5.0453e+00, -0.0000e+00, -1.4279e+01,  0.0000e+00],
        [ 1.5101e+08,  3.5667e+04, -2.4639e+08,  0.0000e+00,  8.7842e+04,
          0.0000e+00, -6.1174e+00,  0.0000e+00,  5.7235e+02, -0.0000e+00]])

In [8]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6 Подсказка: .dot может не подойти
tens2 @ tens2.T

tensor([[18.0431,  0.9342, -2.1215,  1.5814, -1.9849,  3.9431],
        [ 0.9342,  3.1071,  0.5538,  0.6483,  0.1521, -0.0891],
        [-2.1215,  0.5538, 11.4595,  7.6552,  1.5808,  1.9887],
        [ 1.5814,  0.6483,  7.6552, 14.9408,  9.3903,  5.6791],
        [-1.9849,  0.1521,  1.5808,  9.3903, 16.2113, -0.4948],
        [ 3.9431, -0.0891,  1.9887,  5.6791, -0.4948, 13.9399]])

In [9]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
f = torch.Tensor([1, 0.5, 2])
f.requires_grad = True
y = f[0]**3 + f[1] - 75 * f[1]
y.backward()
f.grad

tensor([  3., -74.,   0.])

In [10]:
# Создайте единичный тензор размера 5x6
ones_tens = torch.ones(5, 6)
ones_tens

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [11]:
# Переведите его в формат numpy
ones_tens.numpy()

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)